Add support for environments and services
honeycombio/libhoney-java pull request #121
Opened 2022-03-24 15:38 UTC by MikeGoldsmith

## Which problem is this PR solving?
Updates the Options class to default to "unknown_service" or trim the dataset value if a non-classsic API (write) key is used. Default behaviour for classic API keys is unchanged.

- Closes #119 

## Short description of the changes
- Adds `isClassic` method to Options to check
- Updates `getDataset` to determine if in classic mode or not, if yes then dataset unmodified, if no then either return "unknown_service" or trimmed dataset string

2022-03-24 20:33 UTC, vreynolds requested changes

2022-03-24 20:33 UTC, vreynolds commented on libhoney/src/main/java/io/honeycomb/libhoney/Options.java
> +    public static final String DEFAULT_NON_CLASSIC_DATASET = "unknown_service";
it should be `unknown_dataset`

2022-03-24 20:33 UTC, vreynolds commented on libhoney/src/main/java/io/honeycomb/libhoney/Options.java
> +        return dataset.trim();
we also talked about warning users when the trimming changes the value, so they can fix the discrepancy (like we did in the [go beeline](https://github.com/honeycombio/beeline-go/blob/dcd5cac17320d77d7242d157e4dea6c757edbd03/beeline.go#L146))

2022-03-28 13:53 UTC, MikeGoldsmith commented
Updated as requested, thanks @vreynolds

2022-03-28 14:45 UTC, vreynolds approved these changes

2022-03-28 14:59 UTC, merged